openapi: 3.0.1
info:
  title: gw-file-receiver
  description: synchronization file receiver service
  version: 1.1.4
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /fileReceiver:
    post:
      operationId: receiveFile
      tags:
        - fileReceiver
      summary: save synced file to persistent storage and notify sync manager
      parameters:
        - in: header
          name: filename
          schema:
            type: string
        - in: query
          name: filename
          schema:
            type: string
        - in: query
          name: routeID
          schema:
            type: string
        - in: query
          name: filesize
          schema:
            type: string
      requestBody:
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/binaryFile'
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    binaryFile:
      type: string
      format: binary
