{{- $chartName := include "gw-file-receiver.name" . -}}
{{- $tracingUrl := include "gw-file-receiver.tracingUrl" . -}}
{{- $metricsUrl := include "gw-file-receiver.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  STORAGE_PROVIDER: {{ .Values.env.storage.provider | quote }}
  S3_ENDPOINT_URL: {{ .Values.env.storage.S3.endpointUrl | quote }}
  S3_BUCKET: {{ .Values.env.storage.S3.bucket | quote }}
  S3_SSL_ENABLED: {{ .Values.env.storage.S3.sslEnabled | quote }}
  FS_BASE_PATH: {{ .Values.env.storage.FS.mountRelativeBasePath | quote }}
  SYNC_MANAGER_URL: {{ .Values.env.httpClient.syncManagerUrl | quote }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpClient.retry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpClient.retry.delay | quote }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpClient.retry.shouldResetTimeout | quote }}
{{- end }}
