{{- $releaseName := .Release.Name -}}
{{- $chartName := include "gw-file-receiver.name" . -}}
{{- $cloudProviderFlavor := include "gw-file-receiver.cloudProviderFlavor" . -}}
{{- $cloudProviderDockerRegistryUrl := include "gw-file-receiver.cloudProviderDockerRegistryUrl" . -}}
{{- $imageTag := include "gw-file-receiver.tag" . -}}
{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}-{{ $chartName }}
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "gw-file-receiver.environment" . }}
    release: {{ $releaseName }}
    {{- include "gw-file-receiver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $chartName }}
      release: {{ $releaseName }}
      run: {{ $releaseName }}-{{ $chartName }}
      {{- include "gw-file-receiver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $chartName }}
        release: {{ $releaseName }}
        run: {{ $releaseName }}-{{ $chartName }}
        {{- include "gw-file-receiver.selectorLabels" . | nindent 8 }}
      {{- if .Values.resetOnConfigChange }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- if .Values.cloudProvider.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.cloudProvider.imagePullSecretName | quote }}
      {{- end }}
      {{- if .Values.storage.tilesPvc.enabled }}
      volumes:
        - name: tiles-volume
          persistentVolumeClaim:
            claimName: {{ .Values.storage.tilesPvc.name }}
      {{- end }}
      containers:
        - name: {{ $releaseName }}-{{ $chartName }}-deployment
          {{- with .Values.image }}
          image: {{ $cloudProviderDockerRegistryUrl }}{{ .repository }}:{{ $imageTag }}
          {{- end }}
          {{- if .Values.storage.tilesPvc.enabled }}
          volumeMounts:
            - name: tiles-volume
              mountPath: /tiles
          {{- end }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.env.targetPort | quote }}
            - name: FS_MOUNT_PATH
              value: '/tiles'
            {{- if .Values.env.storage.S3.enabled }}
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.storage.S3.secret.name }}
                  key: accessKeyId
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.storage.S3.secret.name }}
                  key: secretAccessKey
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ $releaseName }}-{{ $chartName }}-configmap
          ports:
            - name: http
              containerPort: {{ .Values.env.targetPort }}
              protocol: {{ .Values.env.protocol }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialDelaySeconds }}
            httpGet:
              path: /liveness
              port: http
          {{- if .Values.resources.enabled }}
          resources:
            {{- toYaml .Values.resources.value | nindent 12 }}
          {{- end }}
{{- end -}}
